name: Compile CV

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Connor_Mullins-CV.tex
          
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: Connor_Mullins-CV.pdf

      - name: Commit PDF to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Connor_Mullins-CV.pdf
          git commit -m "auto-compile pdf" || echo "No changes"
          git push